### ISSUE TITLE
Update addressing memory problem 

### ISSUE THREAD

**Issue by KasperBuskPedersen** [N720720/lindemann#289] opened 2021-12-19 17:38 UTC
Hi 

Is this library still maintained?
It is stated in the Precautions-section that an update will be made when numpy.nanmean has axis functionality. I believe that this is the case now.

I am very interested in using your library for my research and was very excited when I found it. However, I am currently getting segmentation faults running the -f flag on a desktop, presumably because I run out of memory. Systems contains 1000's of atoms, so it could be a problem. Do you have an estimate on the runtime benchmark vs systemsize of the code?

Thank you in advance 
Kasper

**Comment by N720720** [comment] 2022-01-17 20:32
Hey @KasperBuskPedersen ,

thanks for your interest in the project. I apologize for not answering you until now. I just checked again and unfortunately they still haven't moved forward at numba with supporting the axsis option for the numpy nanmean function. 

https://github.com/numba/numba/issues/1269

For the system with 1000 atoms I would guess that there is not enough memory. You can check before how much RAM is needed with the -m flag. This is actually always recommended if you use other flags than the -t flag.

One more remark about the runtime vs. memory usage. I had to take the np.nanmean(axis) part out of the functions to be able to jit them successfully with numba. Therefore the dimensions are reduced by the mean function only at the very end. Therefore the entire process is very memory heavy. Numpy uses highly optimized vectorizations for array operations, which certainly come into play at this point where the array is in the ram and provide good performance, at the expense of memory usage. As mentioned, this circumstance is by necessity and not by design. However, for usual lindemann index calculations with the -t flag are still quite reasonable in terms of memory usage. 

Best regards
Sebastian

**Comment by N720720** [comment] 2022-01-21 21:04
Hey @KasperBuskPedersen ,
thanks again for an issue, it has motivated me once again to take on the problem. The issue at numba has been open for a very long time and therefore it was necessary to find a solution myself. The problem was that in the algoritsmus a trigagonal matrix arises. This matrix is mirrored, but has zeros in the track. This led to nan values in the division. The jit compiled numba function can not handle the required nanmean. This resulted in an array with the dimensions frames,atom,atoms being needed. Which quickly escalated as you can see in the picture:

![Figure_1_trim](https://user-images.githubusercontent.com/65230277/150597693-6791e405-632b-46d2-8b7b-56d957a54548.png)

Now I have completely removed the track with the zeros for the division and I was able to reduce the memory allocation by one dimension. This is the dimension of the frames. The memory allocation is now completely independent of the length of the trajectory.  By the removal of the formation of nans in the algorithm, it is now possible that the reduction of the dimension is done in the loop. np.nanmean is thus no longer necessary and numpy functions can be used that are supported by numba so the function can be jit compiled. You can see the result here:

![Figure_2_new_mem](https://user-images.githubusercontent.com/65230277/150599196-2c78bb49-83f9-4eaa-94ce-c87d40847b31.png)

With version v0.5.0 this feature is implemented. 

I hope this library benefits your research and that you can now use the -f flag to study the development of the lindemann index.

Best regards
Sebastian

**Comment by KasperBuskPedersen** [comment] 2022-01-21 21:43
Dear Sebastian

Thank you for looking into it! This looks excellent. I am already using the library, where I figured out a way to use the -t flag instead. I will definitely check out the -f flag now. 

I am a GROMACS user, so I wrote a small script that deals with the LAMMPS format and divides a gromacs trajectory into small blocks and uses the -t flag on it. I have attached it here, as it might come in handy for other people using your library down the road. 

Best,
Kasper

`#!/usr/bin/env python
#Written by Kasper B. Pedersen, 1-Dec-2021
#This script assumes that the python library lindemann 0.4.0 (https://libraries.io/pypi/lindemann) is installed: pip install lindemann
#Usage: python3 calc_lindemann.py [outfilename] [.xtc] [.gro] [index of first frame] [index of last frame] [number of frames in <r_ij>_T]
import sys
import subprocess
import re
import numpy as np
import mdtraj as md

outfile = sys.argv[1]
xtcfile = sys.argv[2]
grofile = sys.argv[3]
b = int(sys.argv[4]) #in ns
e = int(sys.argv[5])
blocksize = int(sys.argv[6])

blocks = np.arange(b-1,e+blocksize,blocksize)
num_blocks = blocks.shape[0]-1

t = md.load(xtcfile,top=grofile)

i = 0
try:
    i = int(np.loadtxt("temp_{}.log".format(outfile))[-1])
    i += 1
except:
    pass

while i < num_blocks:
    start = blocks[i]+1
    end = blocks[i+1]
    print("Processing frame {}-{}".format(start,end))
    t[start:end].save_lammpstrj("temp_{}.lammpstrj".format(outfile))
    lindemann = subprocess.check_output(['lindemann','-t','temp_{}.lammpstrj'.format(outfile)], stderr=subprocess.PIPE)
    lindemann = str(lindemann)
    lindemann = re.findall("[+-]?\d+\.\d+", lindemann)
    lindemann = float(lindemann[0])
    proc = subprocess.run(['rm', 'temp_{}.lammpstrj'.format(outfile)])
    
    if not i:
        with open(outfile,'w') as f:
            f.write("{}\n".format(lindemann))
        with open("temp_{}.log".format(outfile),'w') as f:
            f.write("{}\n".format(i))
    else:
        with open(outfile,'a') as f:
            f.write("{}\n".format(lindemann))
        with open("temp_{}.log".format(outfile),'a') as f:
            f.write("{}\n".format(i))
    i += 1

print("Done!")`

**Comment by N720720** [comment] 2022-01-26 11:21
Dear @KasperBuskPedersen ,
I am glad that you have found a solution in the meantime. I hope the -f option will be of use to you. I have had a look at your attached python script. I would like to point out that you can use lindemann not only as a CLI tool but also as a Python module. I took the liberty of using your script as a template to show this.

```python
from lindemann.index import per_frames
from lindemann.trajectory import read
import numpy as np
import mdtraj as md
import sys
import os

outfile = sys.argv[1]
xtcfile = sys.argv[2]
grofile = sys.argv[3]

#workaround to use lindemann with GROMACS

temp_file = "temp_{}.lammpstrj".format(outfile)

t = md.load(xtcfile,top=grofile)
t.save_lammpstrj(temp_file)
frames = read.frames(temp_file)

lineman_index_per_frame = per_frames.calculate(frames)

np.savetxt(outfile, lineman_index_per_frame)

try:
    os.remove(temp_file)
except OSError as e: 
    print (f"Error: {e.filename} - {e.strerror}.")
```
I took a look at the mdtraj documentation and source code and noticed that the mdtraj method [t.xyz](https://github.com/mdtraj/mdtraj/blob/51779e2c820df155782ec24f6d9e2701939cc539/mdtraj/core/trajectory.py#L920) returns a numpy array with the same shape (frames, atoms, xyz) as the read method of the lindeman module that uses ovito to read the file. So I think you could get rid of the workaround. It could look something like this:

```python
from lindemann.index import per_frames
import numpy as np
import mdtraj as md
import sys

outfile = sys.argv[1]
xtcfile = sys.argv[2]
grofile = sys.argv[3]

t = md.load(xtcfile,top=grofile)
frames = t.xyz

lineman_index_per_frame = per_frames.calculate(frames)

np.savetxt(outfile, lineman_index_per_frame)
```
Perhaps you could provide me with a sample GROMACS file so I can test this. Ovito also supports a variety of different [formats](https://www.ovito.org/manual/reference/file_formats/file_formats_input.html#file-formats-input) with their [import_file](https://www.ovito.org/manual/python/modules/ovito_io.html#ovito.io.import_file) method that I use. Maybe Iindemann will work with your GROMACS files out of the box, since Ovito supports them.  I've only worked with LAMMPS so far, and since I've only had the chance to test lindemann with lammps trajectories, I haven't included other trajectory file formats that ovito supports.But we could certainly change that for GROMACS.

**Comment by N720720** [comment] 2023-01-05 14:33
Since it looks like no further support is needed, I am closing this issue.

**Closed by N720720** 2023-01-05 14:33 UTC
Labels: enhancement
